### ISSUE TITLE
Updating Currently Running Missions

### ISSUE THREAD

**Issue by bobbleballs** [nvidia-isaac/isaac_mission_dispatch#5]
Hi,
I'm a bit confused about the functionality of the Mission Trees and their surrounding functions. I've had a play with the tool and got it talking to Inorbit's VDA5050 ROS2 Connector and it works fine for a simple Mission. However I am interested in controlling multiple robots at once. In this use-case I will need to update/cancel/pause currently running missions to keep the robots from colliding/congestion occurring.

I have noticed that in the documentation you mention:
`All missions are expected to be idempotent and instead of updating a mission: developers are expected to delete and re-submit.` 
However just above this you also state:
`Similarly, if users want to CANCEL a currently running mission, Mission Dispatch will set needs_canceled in mission specifications to True, wait for the current mission to finish, and then cancel the mission.`
This implies that there is actually no way to Cancel, Delete or Update a currently running mission. Is this correct? If so are there any plans to update this behaviour?

VDA5050 does have this feature baked in and it is quite integral to the standard (See Section 6.2.2 - Orders and order update), I've had a look at your source code and it does seem like it could be updated to support this feature. 
Is there any reason why this was omitted deliberately?

**Comment by nv-delliott** [comment]
Correct, Isaac Mission Dispatch and Mission Client released in Developer Preview 2 do not support cancel, delete, or updating of an actively running mission. Delete is only supported if a mission has not started yet. Beyond simple cancellation of a mission, this functionality is required for a Master Control to update on-task robots actively solving a multi vehicle routing problem. A candidate solution is being tested internally so we can find and resolve corner cases. We may include in our next release if corner cases are sufficiently addressed.

**Comment by nv-delliott** [comment]
We have released an updated version of Mission Dispatch and Mission Client with the release of Isaac ROS 2.0.  We encourage you to check it out.  Since Developer Preview 2 (DP2) we have reworked the cancel/update/delete constructs to function in more scenarios and also aim to be more standards compliant.   
https://discourse.ros.org/t/isaac-ros-2-0-release-at-roscon-2-years-of-accelerating-ros/34234

Tagging Verify to Close for originate to confirm and close.  Please open a new issue if new behavior regresses or there are specific conflicts with standards.
